name: Django CI/CD - Staging (Homologação)

on:
  push:
    branches:
      - homolog
  pull_request:
    branches:
      - homolog

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    #   - name: Set up PostgreSQL
    #     uses: postgres-actions/setup-postgresql@v2
    #     with:
    #       postgresql-version: '13'
    #       postgresql-db: test_db
    #       postgresql-user: postgres
    #       postgresql-password: postgres

      - name: Entrar no diretorio delivery
        run: |
          cd delivery

      - name: Run migrations
        run: |
          cd delivery
          python manage.py migrate

      - name: Run tests
        run: |
          cd delivery
          python manage.py test

#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     environment:
#       name: staging

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy to Staging (exemplo: Heroku)
#         run: |
#           # Aqui você pode adicionar o comando para deploy para homologação
#           echo "Deploy para homologação"
